# Steam Data Collection

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import requests

import utils.steam_scraping_utils as steam_utils
# import list_all_games, get_request_with_retry, get_steam_details

In [3]:
# Set file parameters
download_path = 'data'
steam_ids = 'steam_ids.csv'
steam_app_data = 'steam_app_data.csv'
steam_index = 'steam_index.txt'

steam_test_file = 'steam_tset_file.csv'

In [4]:
games_list = steam_utils.list_all_games(download_path, filename=steam_ids)

games_list.head()

Get list of every game on steamspy sorted by number of owners

     appid                              name
0      570                            Dota 2
1      730  Counter-Strike: Global Offensive
2   578080               PUBG: BATTLEGROUNDS
3  1063730                         New World
4      440                   Team Fortress 2

In [6]:
games_list.iloc[3115]

appid                    313500
name     Blitzkrieg 2 Anthology
Name: 3115, dtype: object

## Retrieving app details using steam API only right now

In [14]:
# steam_utils.get_steam_details(download_path, steam_app_data, games_list,index_filename=steam_index, start=2906, end=10000)

No Response..

Retrying - Retry count:  1
No Response..

Retrying - Retry count:  2
No Response..

Retrying - Retry count:  1
No Response..

Retrying - Retry count:  2
No Response..

Retrying - Retry count:  3
No Response..

Retrying - Retry count:  4
No Response..

Retrying - Retry count:  5
No Response..

Retrying - Retry count:  1
No Response..

Retrying - Retry count:  2
No Response..

Retrying - Retry count:  3
No Response..

Retrying - Retry count:  4
No Response..

Retrying - Retry count:  5

In [5]:
ok = pd.read_csv('data/steam_app_data.csv')

ok

,type,name,steam_appid,required_age,is_free,controller_support,dlc,detailed_description,about_the_game,short_description,...,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu,youtube_stats
0,game,Dota 2,570,0.0,True,NaN,"[1241930, 652720]",<strong>The most-played game on Steam.</strong...,<strong>The most-played game on Steam.</strong...,"Every day, millions of players worldwide enter...",...,"100,000,000 .. 200,000,000",35483,1461,929,852,0,0,0,589010,": 5,475,768 views and 10,283 comments for top ..."
1,game,Counter-Strike: Global Offensive,730,0.0,True,full,[1766730],Counter-Strike: Global Offensive (CS: GO) expa...,Counter-Strike: Global Offensive (CS: GO) expa...,Counter-Strike: Global Offensive (CS: GO) expa...,...,"50,000,000 .. 100,000,000",28940,841,6887,284,0,0,0,862238,": 37,980 views and 208 comments for top 50 vid..."
2,game,PUBG: BATTLEGROUNDS,578080,0.0,True,NaN,NaN,"<strong>LAND, LOOT, SURVIVE!</strong><br>Play ...","<strong>LAND, LOOT, SURVIVE!</strong><br>Play ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,...,"50,000,000 .. 100,000,000",21824,748,8263,188,0,0,0,480133,": 1,832,735 views and 1,248 comments for top 5..."
3,game,New World,1063730,0.0,False,NaN,NaN,<h1>New World - Deluxe Edition</h1><p><img sr...,"Explore a thrilling, open-world MMO filled wit...","Explore a thrilling, open-world MMO filled wit...",...,"50,000,000 .. 100,000,000",9088,1042,3914,1477,3999,3999,0,26231,": 1,075,103 views and 6,332 comments for top 5..."
4,game,Team Fortress 2,440,0.0,True,NaN,[629330],"<p><strong>""The most fun you can have online""<...","<p><strong>""The most fun you can have online""<...",Nine distinct classes provide a broad range of...,...,"50,000,000 .. 100,000,000",9470,965,406,133,0,0,0,71215,": 484,936 views and 2,217 comments for top 50 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,game,Cube - The Jumper,856440,0.0,False,NaN,NaN,The main hero of this game became an ordinary ...,The main hero of this game became an ordinary ...,"In front of you is a touching 2D-platformer, t...",...,"20,000 .. 50,000",13,0,13,0,199,199,0,0,NaN
9996,game,Gemini Wars,216130,0.0,False,NaN,NaN,Decades have passed since war erupted between ...,Decades have passed since war erupted between ...,Take control of a fleet commander returned fro...,...,"20,000 .. 50,000",57,0,92,0,1499,1499,0,0,NaN
9997,game,Snowdome,1131740,0.0,False,NaN,[1389940],"<h2 class=""bb_tag"">Story</h2><br><i><strong>“I...","<h2 class=""bb_tag"">Story</h2><br><i><strong>“I...","For Tan Yan, there is little hope his life wil...",...,"20,000 .. 50,000",0,0,0,0,699,699,0,0,NaN
9998,game,Reignfall,935930,0.0,False,NaN,NaN,"<h2 class=""bb_tag"">The Reign...The Fall</h2><b...","<h2 class=""bb_tag"">The Reign...The Fall</h2><b...",Reignfall is a real-time strategy game with el...,...,"20,000 .. 50,000",0,0,0,0,499,499,0,1,NaN
9999,game,Objective H.A.S.T.E. - Survival Horror Escape,1631170,0.0,False,NaN,NaN,Objective H.A.S.T.E. - is a first-person 3D su...,Objective H.A.S.T.E. - is a first-person 3D su...,Objective H.A.S.T.E. - is a first-person 3D su...,...,"20,000 .. 50,000",0,0,0,0,599,599,0,0,NaN

### Scraping more metacritic scores for the processed_data

In [6]:
processed_data_path = '../processed_data/games_stats.csv'

In [7]:
df = pd.read_csv(processed_data_path)

In [14]:
c = df[df['metacritic_user_score']==0]
c

,Unnamed: 0,name,steam_appid,required_age,is_free,controller_support,developers,publishers,metacritic,metacritic_user_score,...,genre_racing,genre_rpg,genre_sexual_content,genre_simulation,genre_software_training,genre_sports,genre_strategy,genre_utilities,genre_violent,genre_web_publishing
2,2,PUBG: BATTLEGROUNDS,578080,0,1,0,"['KRAFTON, Inc.']","['KRAFTON, Inc.']",0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,5,Unturned,304930,0,1,0,['Smartly Dressed Games'],['Smartly Dressed Games'],0,0.0,...,0,0,0,0,0,0,0,0,0,0
12,12,Brawlhalla,291550,0,1,1,['Blue Mammoth Games'],['Ubisoft'],0,0.0,...,0,0,0,0,0,0,0,0,0,0
14,14,Garry's Mod,4000,0,0,0,['Facepunch Studios'],['Valve'],0,0.0,...,0,0,0,1,0,0,0,0,0,0
15,15,Tom Clancy's Rainbow Six® Siege,359550,0,0,0,['Ubisoft Montreal'],['Ubisoft'],0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9874,9994,Puzzzle,1424250,0,1,0,['Stephen Walton'],['Stephen Walton'],0,0.0,...,0,0,0,1,0,0,0,0,0,0
9875,9995,Cube - The Jumper,856440,0,0,0,['DZEJK'],['Garage Games'],0,0.0,...,0,0,0,0,0,0,0,0,0,0
9877,9997,Snowdome,1131740,0,0,0,['Lunatic Works'],"['Lunatic Works', 'Kikai Digital']",0,0.0,...,0,0,0,0,0,0,0,0,0,0
9878,9998,Reignfall,935930,0,0,0,['Checkmaty'],['Checkmaty'],0,0.0,...,0,0,0,0,0,0,1,0,0,0
9879,9999,Objective H.A.S.T.E. - Survival Horror Escape,1631170,0,0,0,['Sparking Games'],['Sparking Games'],0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
test_df = df.copy()


test_df = test_df.apply(lambda row: steam_utils.get_metacritic_all_scores(row),axis=1)

Current row:  0
Current row:  100
Current row:  200
Current row:  300
Current row:  400
Current row:  500
Current row:  600
Current row:  700
Current row:  800
Current row:  900
Current row:  1000
Current row:  1100
Current row:  1200
Current row:  1300
Current row:  1400
Current row:  1500
Current row:  1600
Current row:  1700
Current row:  1800
Current row:  1900
Current row:  2000
Current row:  2100
Current row:  2200
Current row:  2500
Current row:  2600
Current row:  2700
Current row:  2900
Current row:  3000
Current row:  3100
Current row:  3200
Current row:  3300
Current row:  3500
Current row:  3600
Current row:  3700
Current row:  3800
Current row:  3900
Current row:  4000
Current row:  4200
Current row:  4300
Current row:  4400
Current row:  4500
Current row:  4600
Current row:  4800
Current row:  4900
Current row:  5000
Current row:  5100
Current row:  5200
Current row:  5300
Current row:  5400
Current row:  5500
Current row:  5600
Current row:  5700
Current row:  5800
Current row:  5900
Current row:  6000
Current row:  6100
Current row:  6200
Current row:  6300
Current row:  6400
Current row:  6500
Current row:  6600
Current row:  6700
Current row:  6900
Current row:  7000
Current row:  7200
Current row:  7400
Current row:  7500
Current row:  7600
Current row:  7700
Current row:  7800
Current row:  7900
Current row:  8000
Current row:  8100
Current row:  8200
Current row:  8300
Current row:  8400
Current row:  8500
Current row:  8600
Current row:  8700
Current row:  8800
Current row:  8900
Current row:  9000
Current row:  9100
Current row:  9200
Current row:  9300
Current row:  9400
Current row:  9500
Current row:  9600
Current row:  9700
Current row:  9800

In [12]:
# test_df.head(10)
q = test_df[test_df['metacritic_user_score']==0]
q

,Unnamed: 0,name,steam_appid,required_age,is_free,controller_support,developers,publishers,metacritic,metacritic_user_score,...,genre_racing,genre_rpg,genre_sexual_content,genre_simulation,genre_software_training,genre_sports,genre_strategy,genre_utilities,genre_violent,genre_web_publishing
2,2,PUBG: BATTLEGROUNDS,578080,0,1,0,"['KRAFTON, Inc.']","['KRAFTON, Inc.']",0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
21,21,Valheim,892970,0,0,1,['Iron Gate AB'],['Coffee Stain Publishing'],0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
24,24,Wallpaper Engine,431960,0,0,0,['Wallpaper Engine Team'],['Wallpaper Engine Team'],0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
44,44,Robocraft,301520,0,1,0,['Freejam'],['Freejam'],0.0,0.0,...,0,1,0,1,0,0,0,0,0,0
46,46,Ring of Elysium,755790,0,1,0,['Aurora Studio'],['TCH Scarlet Limited'],0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9872,9992,Chess Evolved Online,1064340,0,1,0,['TheGrandestine'],['TheGrandestine'],0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
9874,9994,Puzzzle,1424250,0,1,0,['Stephen Walton'],['Stephen Walton'],0.0,0.0,...,0,0,0,1,0,0,0,0,0,0
9875,9995,Cube - The Jumper,856440,0,0,0,['DZEJK'],['Garage Games'],0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
9877,9997,Snowdome,1131740,0,0,0,['Lunatic Works'],"['Lunatic Works', 'Kikai Digital']",0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
9878,9998,Reignfall,935930,0,0,0,['Checkmaty'],['Checkmaty'],0.0,0.0,...,0,0,0,0,0,0,1,0,0,0

In [13]:
test_df.to_csv('../processed_data/games_stats_updated.csv', index=True)